### PR TITLE
Add NMD and fix bug in MorisitaOverlap

### PR DESCRIPTION
**Pull request by robertfeldt**
Adding the important NormalizedMultisetDistance (NMD) which is a fast (q-gram/dictionary style) approximation of the very powerful normalized compression distances (NCD).

Sorry but there is also a bug fix to MorisitaOverlap distance in here. I had accidently inverted the MorisitaOverlap calculation so it was the similarity rather than the distance that was calculated. I found this out when comparing to and testing the NMD distance so was not so easy to "separate" the fixes, sorry. Hope ok.

There are a few more distances related to NMD that I might want to add later but having MorisitaOverlap and NMD was the most important so for now this should be ok.

### CODE REVIEW

**Comment by matthieugomez** [comment]
Thanks!

**Comment by matthieugomez** [comment]
I'm not in the literature but what about calling it `NormalizedMultiset` (and removing the `NMD` acronym)?. The current name is a bit inconsistent with other distances (which do not have `Distance` in their name).

**Comment by robertfeldt** [comment]
I considered it but since a multiset is it's own abstraction / mathematical concept it feels a bit weird calling it a NormalizedMultiset. Skipping the acronym is fine but I couldn't come up with a good solution for the full name...

**Comment by matthieugomez** [comment]
Then maybe only NMD as a name? The acronym is used in the paper so that seems ok for a name.

**Comment by robertfeldt** [comment]
Ok, yes, that works for me. The docstring can have the full name to clarify but the type can be only NMD. Yeah, that should be fine. People say "the NMD distance" anyway so makes sense. Good one.

**Pull request merged**
